# Generated by Django 5.2.5 on 2025-09-10 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=50)),
                ('messageClient', models.TextField()),
                ('dateTem', models.DateTimeField(auto_now_add=True)),
                ('note', models.PositiveIntegerField(default=5)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temoignage_cree', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
