# Generated by Django 5.2.5 on 2025-09-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temoin/'),
        ),
    ]
