# Generated by Django 5.2.5 on 2025-10-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0002_temoignage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
