# Generated by Django 5.2.5 on 2025-10-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0003_temoignage_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
