# Generated by Django 5.2.5 on 2025-10-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0004_temoignage_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='prenomClient',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='nomClient',
            field=models.CharField(max_length=100),
        ),
    ]
