# Generated by Django 5.2.5 on 2025-11-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0005_temoignage_prenomclient_alter_temoignage_nomclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
