# Generated by Django 5.2.5 on 2026-01-10 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscription', '0006_alter_inscription_dateinscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_etudiant', to='inscription.inscription')),
            ],
        ),
    ]
