# Generated by Django 5.2.5 on 2026-01-09 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
        ('service', '0006_categorie_button_service_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='qr_code_url',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.service'),
        ),
    ]
