# Generated by Django 5.2.5 on 2025-09-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_alter_utilisateur_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employe', 'Employé')], default='employe', max_length=20),
        ),
    ]
