# Generated by Django 5.2.5 on 2025-09-10 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_alter_service_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=50)),
                ('prenomClient', models.CharField(max_length=50)),
                ('emailClient', models.EmailField(max_length=254)),
                ('telephoneClient', models.CharField(blank=True, max_length=20, null=True)),
                ('dateInscription', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscription_crees', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='service.service')),
            ],
        ),
    ]
