# Generated by Django 5.2.5 on 2025-09-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
        ('service', '0004_categorie_alter_service_nom_alter_service_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscription_categorie', to='service.categorie'),
        ),
    ]
