# Generated by Django 5.2.5 on 2025-10-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_inscription_categorie'),
        ('service', '0006_categorie_button_service_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='service',
        ),
        migrations.AddField(
            model_name='inscription',
            name='service',
            field=models.ManyToManyField(related_name='inscriptions', to='service.service'),
        ),
    ]
