# Generated by Django 5.2.5 on 2025-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_remove_inscription_service_inscription_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
