# Generated by Django 5.2.5 on 2026-01-09 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_rename_valide_inscription_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='dateInscription',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
