# Generated by Django 5.2.5 on 2025-10-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_commande_categorie'),
        ('service', '0006_categorie_button_service_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='service',
        ),
        migrations.AddField(
            model_name='commande',
            name='service',
            field=models.ManyToManyField(related_name='commandes', to='service.service'),
        ),
    ]
