# Generated by Django 5.2.5 on 2025-10-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_remove_commande_service_commande_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
