# Generated by Django 5.2.5 on 2025-10-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_commande_valide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='valide',
            new_name='statut',
        ),
    ]
