# Generated by Django 5.2.5 on 2025-09-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_categorie_alter_service_nom_alter_service_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categorie/'),
        ),
    ]
