# Generated by Django 5.2.5 on 2025-10-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_categorie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='button',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='button',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
