# Generated by Django 5.2.5 on 2025-10-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipe/')),
                ('role', models.TextField()),
            ],
        ),
    ]
