# Generated by Django 5.2.5 on 2025-10-28 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showreel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='showreel',
            old_name='lien',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='showreel',
            name='titre',
        ),
        migrations.AddField(
            model_name='showreel',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='showreel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showreel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showreels', to=settings.AUTH_USER_MODEL),
        ),
    ]
