# Generated by Django 5.2.5 on 2025-10-27 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projet_user'),
        ('service', '0006_categorie_button_service_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
