# Generated by Django 5.2.5 on 2025-10-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projet_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='titre_projet',
            field=models.CharField(max_length=100),
        ),
    ]
