# Generated by Django 5.2.5 on 2025-09-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='titre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
