# Generated by Django 5.2.5 on 2025-10-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
