# Generated by Django 5.2.5 on 2025-09-10 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreActu', models.CharField(max_length=50)),
                ('contenuActu', models.TextField()),
                ('imageActu', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('datePub', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Actualite_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
