# Generated by Django 5.2.5 on 2026-01-09 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='datePub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
